name = "Gangcraft Definitive Edition"
author = "Barry_Alen077"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e17980b7cb78f234a4fd4649f0f99f347f1e5cd7ea9d196fef640b52c58a9dda"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
