name = "Gangcraft Definitive Edition"
author = "Barry_Alen077"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcf524906ed36eeb6266f55d3d07d2882c33c164fc89bb375b88aa8feba7a974"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
