name = "Gangcraft Definitive Edition"
author = "Barry_Alen077"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f917b865543ba9737949de833a32101c23b39a39e2d770dbfb55239a555d05c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
